### ISSUE TITLE
Creare connessione tra questo repo e il canale Slack #strumenti

### ISSUE THREAD

**Issue by lorenzoperone** [Witnessjournal/wj-tech#2]
Vorrei che le nuove issue venissero citate nel canale

**Comment by pbosetti** [comment]
I Webhook non funzionano (hanno una struttura JSON non compatibile con quello di slack). Ho quindi impostato la app GitHub in Slack.
I comandi sono: `/invite @github` e poi `/github subscribe organization/repo`
